### ISSUE TITLE
Client.on("ready", () => function{}); firing too many times

### ISSUE THREAD

**Issue by Eytukan** [Eytukan/Eytoucan#1]
I have no idea why this is happening, if you do please help.

**Comment by BlazeProgramming** [comment]
Try, perhaps, not using arrow function syntax? Perhaps that would help.

**Comment by raumaankidwai** [comment]
Yes, actually it might be the cause. It's wrong syntax.

**Comment by raumaankidwai** [comment]
I mean `() => function {}` is wrong.

**Comment by BlazeProgramming** [comment]
I knew that looked wrong xD

**Comment by Eytukan** [comment]
Sure I will try that

**Comment by Eytukan** [comment]
nah now it does it multiple times without repeating. Arrow function worked the same :1

**Comment by Eytukan** [comment]
fixed somehow idk
